<a href="https://colab.research.google.com/github/keyvanforwork/deep-learning-with-TensorFlow/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introducing to tensors

In [ ]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
# Create a scaler
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Number of dimensions for tensors
scaler.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix (more than 1 dimensions)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix1 = tf.constant([[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.]], dtype= tf.float16)
matrix1

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [ ]:
matrix1.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* **scaler**: a single number
* **vector**: a number with direction
* **matrix**: a 2-dimensional array of numbers
* **tensor**: an n-dimensional array of numbers  (n can be any number, 0-dimension tensor is a scaler, 1-dimension tensor is a vector, 2-dimension tensor is a matrix, ... )
           
      

In [ ]:
# Create tensors with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

NameError: ignored

In [ ]:
# changeable_tensor[0] = 4     # erorr
changeable_tensor[0].assign(4)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Shuffle a tensor (use for shuffling our data)
tensor1 = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9],
                       [8, 9, 1, 5, 4, 4, 9, 1, 3],
                       [1, 6, 6, 8, 2, 6, 9, 1, 7]])
tf.random.shuffle(tensor1)

<tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[8, 9, 1, 5, 4, 4, 9, 1, 3],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 6, 6, 8, 2, 6, 9, 1, 7]], dtype=int32)>

In [ ]:
tensor2 = tf.constant([[[1, 2],
                        [3, 4],
                        [8, 9]],
                       [[5, 6],
                        [7, 8],
                        [10, 11]]])
print(tensor2.ndim)
tf.random.shuffle(tensor2)

3


<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 8,  9]],

       [[ 5,  6],
        [ 7,  8],
        [10, 11]]], dtype=int32)>

In [ ]:
tf.random.shuffle(tensor1, seed= 42)

<tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[8, 9, 1, 5, 4, 4, 9, 1, 3],
       [1, 6, 6, 8, 2, 6, 9, 1, 7],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)       # global seed
tf.random.shuffle(tensor1, seed= 42)   # operation-level seed

<tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [8, 9, 1, 5, 4, 4, 9, 1, 3],
       [1, 6, 6, 8, 2, 6, 9, 1, 7]], dtype=int32)>

In [ ]:
tensor_1 = tf.random.Generator.from_seed(42)
tensor_1 = tensor_1.normal(shape=(7, 4))
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
       [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ]],
      dtype=float32)>

In [ ]:
tf.ones((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros((5, 2))

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
# Turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype= np.int64)
A= tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, A.shape, tf.size(A), A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 TensorShape([2, 3, 4]),
 <tf.Tensor: shape=(), dtype=int32, numpy=24>,
 3)

In [ ]:
rank_4_tensor = tf.zeros(shape=(2, 4, 3, 6))
rank_4_tensor

<tf.Tensor: shape=(2, 4, 3, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[1]

<tf.Tensor: shape=(4, 3, 6), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor), rank_4_tensor.dtype

(TensorShape([2, 4, 3, 6]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=144>,
 tf.float32)

In [ ]:
rank_4_tensor[-1, -1, -1 , -1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
print(tf.size(rank_4_tensor))
print(tf.size(rank_4_tensor).dtype)
print(tf.size(rank_4_tensor).numpy())

tf.Tensor(144, shape=(), dtype=int32)
<dtype: 'int32'>
144


In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.ones(shape=(4, 2))
rank_2_tensor

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[1, 4],
                             [7, 3]])
rank_3_tensor = rank_2_tensor[:, tf.newaxis, :]
rank_3_tensor

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 4]],

       [[7, 3]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[7],
        [3]]], dtype=int32)>

In [ ]:
tensor_1 = rank_2_tensor[:, tf.newaxis]
tensor_1

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 4]],

       [[7, 3]]], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [4]],

       [[7],
        [3]]], dtype=int32)>

### Manipulating tensors

In [ ]:
# Basic operations
tensor_1 = tf.constant([[1, 4],
                        [7, 9]])
print(tensor_1 + 10)
print(tensor_1 - 10)
print(tensor_1 * 10)
print(tensor_1 / 10)

tf.Tensor(
[[11 14]
 [17 19]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -6]
 [-3 -1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 40]
 [70 90]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.4]
 [0.7 0.9]], shape=(2, 2), dtype=float64)


In [ ]:
# Tensot flow built-in basic operator
tensor_1 = tf.constant([[1, 4],
                       [7, 9]])
print(tf.add(tensor_1, 10))
print(tf.subtract(tensor_1, 10))
print(tf.multiply(tensor_1, 10))
print(tf.divide(tensor_1, 10))

tf.Tensor(
[[11 14]
 [17 19]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -6]
 [-3 -1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 40]
 [70 90]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.4]
 [0.7 0.9]], shape=(2, 2), dtype=float64)


In [ ]:
# Matrix muitiplicaton (dot product) in tensorflow
tensor_1 = tf.constant([[6, 8],
                        [7, 9]])
print(tf.matmul(tensor_1, tensor_1))
print(tensor_1 * tensor_1)  # element-wise multiply
print(tensor_1 @ tensor_1)  # matrix multiplication in python

tf.Tensor(
[[ 92 120]
 [105 137]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[36 64]
 [49 81]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 92 120]
 [105 137]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_1 = tf.constant([[4, 7],
                        [5, 8],
                        [6, 9]])  # shape=(3, 2)
tensor_2 = tf.constant([[8, 7],
                        [5, 3],
                        [1, 2]])  # shape=(3, 2)
# tf.matmul(tensor_1, tensor_2)   # error for shape incompatible

In [ ]:
tensor_1 = tf.constant([[4, 7],
                        [5, 8],
                        [6, 9]])  # shape=(3, 2)
tensor_2 = tf.constant([[8, 7],
                        [5, 3],
                        [1, 2]])  # shape=(3, 2)
tensor_2_reshaped = tf.reshape(tensor_2, shape=(2, 3))
tf.matmul(tensor_1, tensor_2_reshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[53, 35, 34],
       [64, 43, 41],
       [75, 51, 48]], dtype=int32)>

In [ ]:
tensor_1 = tf.constant([[4, 7],
                        [5, 8],
                        [6, 9]])  # shape=(3, 2)
tensor_2 = tf.constant([[8, 7],
                        [5, 3],
                        [1, 2]])  # shape=(3, 2)
tensor_2_transposed = tf.transpose(tensor_2)
tf.matmul(tensor_1, tensor_2_transposed)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 81,  41,  18],
       [ 96,  49,  21],
       [111,  57,  24]], dtype=int32)>

In [ ]:
tf.tensordot(tensor_1, tensor_2_transposed, axes= 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 81,  41,  18],
       [ 96,  49,  21],
       [111,  57,  24]], dtype=int32)>

#### Changing the dtypes

In [ ]:
A = tf.constant([1.5, 7.4, 9.2])
print(A.dtype)
B = tf.constant([1, 4, 2])
print(B.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


In [ ]:
C = tf.cast(A, dtype= tf.float16)
print(C.dtype)
D = tf.cast(B, dtype= tf.int16)
print(D.dtype)
E = tf.cast(B, dtype= tf.float32)
print(E)
print(E.dtype)

<dtype: 'float16'>
<dtype: 'int16'>
tf.Tensor([1. 4. 2.], shape=(3,), dtype=float32)
<dtype: 'float32'>


#### Aggregation tensors

In [ ]:
# Get the absolute values
tensor_1 = tf.constant([-2, -5, -8, -6])
tf.abs(tensor_1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 5, 8, 6], dtype=int32)>

In [ ]:
import numpy as np
tensor_1 = tf.constant(np.random.randint(0, 100, size= 50))
tensor_1

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([40, 66, 79, 79, 14, 75, 92, 93, 76, 37, 69, 84, 10, 59,  5, 63, 64,
       75, 25, 43, 91, 53, 76, 57, 43, 82, 80, 82, 42, 44, 40, 53, 64, 21,
        9, 23, 46, 96, 50,  3,  8, 56, 79, 21, 37, 55, 89, 36, 93, 16])>

In [ ]:
len(tensor_1), tf.size(tensor_1), tensor_1.shape, tensor_1.ndim

(50, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
print(tf.reduce_min(tensor_1))
print(tf.reduce_max(tensor_1))
print(tf.reduce_mean(tensor_1))
print(tf.reduce_sum(tensor_1))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(96, shape=(), dtype=int64)
tf.Tensor(53, shape=(), dtype=int64)
tf.Tensor(2693, shape=(), dtype=int64)


In [ ]:
import tensorflow_probability as tfp
print(tfp.stats.variance(tensor_1))
print(tf.math.reduce_variance(tf.cast(tensor_1, dtype= tf.float32)))

tf.Tensor(728, shape=(), dtype=int64)
tf.Tensor(727.3204, shape=(), dtype=float32)


In [ ]:
print(tf.math.reduce_std(tf.cast(tensor_1, dtype= tf.float32)))

tf.Tensor(26.968878, shape=(), dtype=float32)


In [ ]:
# Find the positional max and min (index)
tf.random.set_seed(42)
tensor_1 = tf.random.uniform(shape=[250])
print(tensor_1[:10])

print(tf.argmax(tensor_1)) # index
print(tf.argmin(tensor_1)) # index

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686], shape=(10,), dtype=float32)
tf.Tensor(201, shape=(), dtype=int64)
tf.Tensor(236, shape=(), dtype=int64)


In [ ]:
print(tensor_1[tf.argmax(tensor_1)])  # value
print(tensor_1[tf.argmin(tensor_1)])  # value

tf.Tensor(0.9823284, shape=(), dtype=float32)
tf.Tensor(0.00030374527, shape=(), dtype=float32)


In [ ]:
print(tensor_1[tf.argmax(tensor_1)] == tf.reduce_max(tensor_1))
print(tensor_1[tf.argmin(tensor_1)] == tf.reduce_min(tensor_1))

tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)


#### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
tensor_1 = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1 ,1, 50))
tensor_1

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
tensor_1.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
tensor_1_squeezed = tf.squeeze(tensor_1)
tensor_1_squeezed, tensor_1_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

#### One-hot encoding tensor

In [ ]:
color = ["Green", "Red", "Blue", "Yellow"]
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth= 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth= 4, on_value= "Yes", off_value= "No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

#### Square, Squreroot, log

In [ ]:
tensor_1 = tf.range(1, 10)
tensor_1

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(tensor_1)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(tensor_1, dtype= tf.float64))   # not int data type

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

In [ ]:
tf.math.log(tf.cast(tensor_1, dtype= tf.float32))   # not int data type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

#### TensorFlow and NumPy

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
tensor_1 = tf.constant(np.array([1, 2, 3, 4.]))
tensor_1

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [ ]:
type(tensor_1), tensor_1.dtype, tf.size(tensor_1), tensor_1.shape


(tensorflow.python.framework.ops.EagerTensor,
 tf.float64,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 TensorShape([4]))

In [ ]:
array_1 = np.array(tensor_1)
array_1

array([1., 2., 3., 4.])

In [ ]:
type(array_1), array_1.dtype, array_1.size, array_1.shape

(numpy.ndarray, dtype('float64'), 4, (4,))

In [ ]:
tensor_1.numpy(), type(tensor_1.numpy())

(array([1., 2., 3., 4.]), numpy.ndarray)

In [ ]:
tensor_1.numpy()[0], tensor_1[0]

(1.0, <tf.Tensor: shape=(), dtype=float64, numpy=1.0>)

#### **Access to GPUs**

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
